import os
import json
import pandas as pd
from datetime import datetime

def export_to_json(captions_file, output_json):
    """
    Export captions.txt to Hugging Face-style JSON: [{"image": ..., "text": ...}, ...]
    """
    df = pd.read_csv(captions_file, sep='\t', header=None, names=['image', 'text'])
    records = df.to_dict(orient='records')
    with open(output_json, 'w', encoding='utf-8') as f:
        json.dump(records, f, ensure_ascii=False, indent=2)
    print(f"Exported dataset to {output_json}")

def write_summary(summary_path, info):
    """
    Write a summary.txt file with dataset generation info.
    info: dict with keys: prompt, keywords, stats, total_images, resolution, time, gpu_status, author
    """
    lines = []
    lines.append(f"Prompt: {info.get('prompt')}")
    lines.append(f"Expanded Keywords: {', '.join(info.get('keywords', []))}")
    lines.append("")
    lines.append("Images per Keyword:")
    for kw, n in info.get('stats', {}).items():
        lines.append(f"  {kw}: {n}")
    lines.append("")
    lines.append(f"Total Images: {info.get('total_images')}")
    lines.append(f"Selected Resolution: {info.get('resolution')}")
    lines.append(f"Time Taken: {info.get('time'):.1f} seconds")
    lines.append(f"GPU for Captioning: {'Yes' if info.get('gpu_status') else 'No'}")
    lines.append("")
    lines.append(f"Generated by Shakti v1.0 (Author: Akshit, {datetime.now().year})")
    with open(summary_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"Summary written to {summary_path}") 